import Vue from "vue";
import {
    Button,
    Tabbar,
    TabbarItem,
    Toast,
    Row,
    Col,
    Icon,
    Cell,
    CellGroup,
    NavBar,
    Tab,
    Tabs,
    Tag,
    Image,
    NoticeBar,
    Switch,
    DropdownMenu,
    DropdownItem,
    List,
    Dialog,
    Panel,
    Field,
    Uploader,
    ImagePreview,
    Collapse,
    CollapseItem
} from "vant";

Vue.use(Collapse).use(CollapseItem);
Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Toast);
Vue.use(Row);
Vue.use(Col);
Vue.use(Icon);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(NavBar);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Tag);
Vue.use(Image);
Vue.use(NoticeBar);
Vue.use(Switch);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(List);
Vue.use(Dialog);
Vue.use(Panel);
Vue.use(Field);
Vue.use(Uploader);
Vue.use(ImagePreview);
